In [1]:
#Import libraries
import numpy as np
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [109]:
#Range of years
years = np.arange(1991,2019).tolist()
years

[1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018]

In [103]:
#Check to see if the website allows scraping
url = 'https://fred.stlouisfed.org/release/tables?rid=118&eid=259194'
page = requests.get(url)
page

In [132]:
for i in years:
    full_link = url+'&od='+str(i)+'-01-01#'
    page = requests.get(full_link)
    
    #Grab the components - make the soup
    soup = BeautifulSoup(page.text,'lxml')


    #Grab the states and make a dataframe
    states = soup.find_all('span',class_='fred-rls-elm-nm')



    states_list = []
    for i in states:
        state_name = i.text
        states_list.append(state_name)

    states_df = pd.DataFrame(states_list,columns=['State'])
    states_df['index'] = np.arange(len(states_df))
    #states_df['Year'] = str(i)

    #Grab the population values and make a dataframe
    pops = soup.find_all('td',class_='fred-rls-elm-vl-td')


    pop_list = []
    for i in pops:
        pop_num = i.text
        pop_list.append(pop_num)



    pop_df = pd.DataFrame(pop_list,columns=['Pop'])

    pop_df['Pop'] = pop_df['Pop'].replace('\n',"",regex=True).str.strip()
    pop_df['Pop'] = pop_df['Pop'].replace(',',"",regex=True)
    pop_df = pop_df.apply(pd.to_numeric,errors='ignore')
    pop_df = pop_df.iloc[::3, :]
    pop_df['Pop'] = (pop_df['Pop']*1000).astype(int)
    pop_df['index'] = np.arange(len(pop_df))
    #pop_df['Year'] = str(i)


    df = pd.merge(
        states_df,
        pop_df,
        how='left',
        on=['index','Year']
    )
    
    df.head()
    

#     for i in list_of_dfs
#     full_df = pd.concat(list_of_dfs, ignore_index = True)

In [133]:
df

,State,index,Year,Pop
0,Alabama,0,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
1,Alaska,1,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
2,Arizona,2,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
3,Arkansas,3,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
4,California,4,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
5,Colorado,5,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
6,Connecticut,6,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
7,Delaware,7,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
8,District of Columbia,8,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
9,Florida,9,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
10,Georgia,10,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
11,Hawaii,11,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
12,Idaho,12,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
13,Illinois,13,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
14,Indiana,14,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
15,Iowa,15,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
16,Kansas,16,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
17,Kentucky,17,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
18,Louisiana,18,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
19,Maine,19,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
20,Maryland,20,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
21,Massachusetts,21,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
22,Michigan,22,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
23,Minnesota,23,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
24,Mississippi,24,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
25,Missouri,25,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
26,Montana,26,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
27,Nebraska,27,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
28,Nevada,28,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
29,New Hampshire,29,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
30,New Jersey,30,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
31,New Mexico,31,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
32,New York,32,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
33,North Carolina,33,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
34,North Dakota,34,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
35,Ohio,35,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
36,Oklahoma,36,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
37,Oregon,37,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
38,Pennsylvania,38,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
39,Rhode Island,39,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
40,South Carolina,40,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
41,South Dakota,41,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
42,Tennessee,42,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
43,Texas,43,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
44,Utah,44,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
45,Vermont,45,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
46,Virginia,46,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
47,Washington,47,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
48,West Virginia,48,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
49,Wisconsin,49,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN
50,Wyoming,50,"<span class=""fred-rls-elm-nm""><a href=""/series...",NaN

In [101]:
#Set up dataframe
full_df = pd.DataFrame(
    {
        'State':[''], 
        'Year':[''],
        'Population':['']
    }
)
full_df

  State Year Population
0

In [113]:
for i in years:
    full_link = url+'&od='+str(i)+'-01-01#'
    page = requests.get(full_link)
    soup = BeautifulSoup(page.text,'lxml')
    
    
    
    
    states = soup.find_all('span',class_='fred-rls-elm-nm')
    states_list = []
    for i in states:
        state_name = i.text
        states_list.append(state_name)

    states_df = pd.DataFrame(states_list,columns=['State'])
    states_df['index'] = np.arange(len(states_df))
    
    
    
    pops = soup.find_all('td',class_='fred-rls-elm-vl-td')


    pop_list = []
    for i in pops:
        pop_num = i.text
        pop_list.append(pop_num)



    pop_df = pd.DataFrame(pop_list,columns=['Pop'])

    pop_df['Pop'] = pop_df['Pop'].replace('\n',"",regex=True).str.strip()
    pop_df['Pop'] = pop_df['Pop'].replace(',',"",regex=True)
    pop_df = pop_df.apply(pd.to_numeric,errors='ignore')
    pop_df = pop_df.iloc[::3, :]
    pop_df['Pop'] = (pop_df['Pop']*1000).astype(int)
    pop_df['index'] = np.arange(len(pop_df))
    
    full_df = pd.merge(
        states_df,
        pop_df,
        how='left',
        on=['index']
    )
    
    year = i
    df = df.append({
            'State':full_df['State'], 
            'Year':year,
            'Population':full_df['Pop']
    },ignore_index=True)
    
    

df.head()

,1,2,Population,State,Year
0,1.0,a,NaN,NaN,NaN
1,2.0,b,NaN,NaN,NaN
2,NaN,NaN,0 4091025 3 569273 6 376239...,0 Alabama 1 ...,[\n 453.401\n ...
3,NaN,NaN,0 4139269 3 587073 6 386733...,0 Alabama 1 ...,[\n 457.739\n ...
4,NaN,NaN,0 4193113 3 596993 6 399339...,0 Alabama 1 ...,[\n 463.491\n ...

In [111]:
full_link = url+'&od='+str(years[0])+'-01-01#'
full_link

'https://fred.stlouisfed.org/release/tables?rid=118&eid=259194&od=1991-01-01#'